name: Backend

on:
  push:
    branches:
    - master
    paths:
    - Backend/**/*.py
  pull_request:
    branches:
    - master
    paths:
    - Backend/**/*.py

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: Backend

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 --count --exit-zero --max-complexity=10 --max-line-length=999 --statistics
      working-directory: Backend

    - name: Test with pytest
      run: |
        # install pytest and useful wrappers
        pip install pytest
        pip install pytest-asyncio
        pip install pytest_mock
        pip install aiosqlite
        pip install httpx

        # make sure the db runs
        docker-compose run -d --service-ports postgres

        # add the env varible we need to connect to the db
        export $(grep -v '^#' .env | xargs -d '\n')

        # add the backend dir to pythonpath
        export PYTHONPATH="${PYTHONPATH}:/home/runner/work/elevatorbot/elevatorbot/Backend"

        # rename the settings file
        sudo mv rename_to_settings.py settings.py

        # run tests
        pytest Backend
