name: Test ElevatorBot

on:
  push:
    branches:
    - master
    paths:
    - ElevatorBot/**/*.py
  pull_request:
    branches:
    - master
    paths:
    - ElevatorBot/**/*.py

jobs:
  python-tests:
    name: Test ElevatorBot

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ElevatorBot

    - name: Test with pytest
      run: |
        # install pytest and useful wrappers
        pip install pytest
        pip install pytest-asyncio
        pip install pytest_mock

        # rename the settings file
        sudo mv rename_to_settings.py settings.py

        # run tests
        pytest ElevatorBot
